os arch

diff --git a/k b/k
--- a/k
+++ b/k
@@ -11,8 +11,15 @@ then
     LOCALBIN="~/.local/bin"
   fi
 
+  OS=$(uname -s | tr [A-Z] [a-z])
+  case "${OS}" in
+      linux*)     ARCH=$(dpkg --print-architecture);;
+      darwin*)    ARCH=$(uname -m);;
+      *)          echo "error retrieving arch"; exit 1;;
+  esac
+
   KUBECTLBIN="${LOCALBIN}/kubectl"
-  curl -sSLo "$KUBECTLBIN" "https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/${OS}/${ARCH}/kubectl"
+  curl -sSLo "$KUBECTLBIN" "https://storage.googleapis.com/kubernetes-release/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/${OS}/${ARCH}/kubectl"
   chmod +x "$KUBECTLBIN"
 fi
 
